create table if not exists public.admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz default now());
create table if not exists public.products(id bigint generated by default as identity primary key,slug text unique not null,name text not null,description text default '',local_image text default '',image_url text default '',page_url text not null,available boolean not null default true,prices jsonb not null default '{}'::jsonb,from_price numeric(10,2),sort_order integer not null default 0,updated_at timestamptz default now());
alter table public.admins enable row level security; alter table public.products enable row level security;
revoke all on public.admins from anon,authenticated; revoke all on public.products from anon,authenticated;
grant select on public.products to anon,authenticated; grant update on public.products to authenticated; grant select on public.admins to authenticated;
drop policy if exists "public read products" on public.products; create policy "public read products" on public.products for select to anon,authenticated using(true);
drop policy if exists "admin membership" on public.admins; create policy "admin membership" on public.admins for select to authenticated using(user_id=auth.uid());
drop policy if exists "admin update products" on public.products; create policy "admin update products" on public.products for update to authenticated using(exists(select 1 from public.admins a where a.user_id=auth.uid())) with check(exists(select 1 from public.admins a where a.user_id=auth.uid()));
insert into public.products(slug,name,description,local_image,page_url,available,prices,from_price,sort_order) values
('gris','Piedra Gris','Canto rodado gris natural.','img/piedra1.jpg','piedraGris.html',true,'{"1–2": {"20": 45, "40": 60}, "2–3": {"20": 30, "40": 50}, "3–5": {"20": 15, "40": 30}}'::jsonb,15,1),
('mixta','Piedra Mixta','Combinación de tonos naturales.','img/piedra3.jpg','piedraMixta.html',true,'{"1–2": {"20": 25, "40": 44}, "2–3": {"20": 18, "40": 32}, "3–5": {"20": 12, "40": 20}}'::jsonb,12,2),
('beige','Piedra Beige','Tonos cálidos para exteriores y decoración.','img/piedrabeige.jpg','piedraBeige.html',true,'{"1–2": {"20": 32, "40": 54}, "2–3": {"20": 20, "40": 34}, "3–5": {"20": 15, "40": 25}}'::jsonb,15,3),
('roja','Piedra Roja','Color intenso para crear contraste.','img/piedraRoja.jpg','piedraRoja.html',true,'{"1–2": {"20": 35, "40": 60}, "2–3": {"20": 25, "40": 40}, "3–5": {"20": 19, "40": 33}}'::jsonb,19,4),
('blanca','Piedra Blanca','Acabado claro para espacios modernos.','img/piedraBlanca.jpg','piedraBlanca.html',true,'{"1–2": {"20": 40, "40": 72}, "2–3": {"20": 30, "40": 52}, "3–5": {"20": 22, "40": 37}}'::jsonb,22,5),
('lunar','Piedra Lunar','Patrones y tonalidades naturales distintivas.','img/piedra_lunar.jpg','piedralunar.html',true,'{"1–2": {"20": 32, "40": 59}, "2–3": {"20": 24, "40": 40}, "3–5": {"20": 18, "40": 30}}'::jsonb,18,6),
('pulida','Piedra Pulida','Superficie suave para acabados decorativos.','img/piedra_pulida.jpg','piedraPulida.html',true,'{"1–2": {"20": 45, "40": 60}, "2–3": {"20": 30, "40": 50}, "3–5": {"20": 15, "40": 30}}'::jsonb,15,7) on conflict(slug) do update set name=excluded.name,description=excluded.description,local_image=excluded.local_image,page_url=excluded.page_url,prices=excluded.prices,from_price=excluded.from_price,sort_order=excluded.sort_order;
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;
drop policy if exists "public product images" on storage.objects; create policy "public product images" on storage.objects for select to public using(bucket_id='product-images');
drop policy if exists "admin upload product images" on storage.objects; create policy "admin upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));
-- Luego crea el usuario en Authentication > Users y ejecuta:
-- insert into public.admins(user_id) values ('UUID-DEL-USUARIO');
